# Generated by Django 4.2.20 on 2026-03-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('coil_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='reciept date ')),
                ('grade', models.CharField(max_length=10)),
                ('size', models.DecimalField(decimal_places=3, max_digits=10)),
                ('company', models.CharField(max_length=10)),
                ('vendor', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('heat_no', models.CharField(max_length=8)),
            ],
        ),
    ]
