# Generated by Django 4.2.20 on 2026-03-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_company_alter_material_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='reciept date '),
        ),
    ]
