# Generated by Django 4.2.30 on 2026-05-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_coilpart_processstep_productionjob_producttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
