# Generated by Django 4.2.30 on 2026-05-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_change_quantity_to_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
