# Generated by Django 4.2.20 on 2026-05-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_form',
            field=models.CharField(blank=True, choices=[('coil', 'Coil'), ('bar', 'Bar')], max_length=10, verbose_name='Delivery Form'),
        ),
        migrations.AddField(
            model_name='order',
            name='drawing_dimensions',
            field=models.TextField(blank=True, verbose_name='Drawing / Dimensions'),
        ),
        migrations.AddField(
            model_name='order',
            name='end_usage',
            field=models.TextField(blank=True, verbose_name='End Usage / Application'),
        ),
        migrations.AddField(
            model_name='order',
            name='frequency',
            field=models.CharField(blank=True, choices=[('one_time', 'One Time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('as_required', 'As Required')], max_length=20, verbose_name='Frequency'),
        ),
        migrations.AddField(
            model_name='order',
            name='grade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Grade of Material'),
        ),
        migrations.AddField(
            model_name='order',
            name='mechanical_properties',
            field=models.TextField(blank=True, verbose_name='Mechanical Properties'),
        ),
        migrations.AddField(
            model_name='order',
            name='mill_make',
            field=models.CharField(blank=True, max_length=100, verbose_name='Specific Mill Make'),
        ),
        migrations.AddField(
            model_name='order',
            name='processes',
            field=models.TextField(blank=True, verbose_name='Processes (drilling, tapping, etc.)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Required Quantity (kg)'),
        ),
    ]
