# Generated by Django 4.2.20 on 2026-05-16 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_remove_order_size_order_delivery_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='quote_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
