# Generated by Django 4.2.20 on 2026-05-17 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_customer_email_customer_phone_customer_quote_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='materials.producttype', verbose_name='Product Type'),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='materials.order'),
        ),
        migrations.CreateModel(
            name='AllowedCoilSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=10, verbose_name='Grade')),
                ('size', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Size (mm)')),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_specs', to='materials.producttype')),
            ],
        ),
    ]
