# Generated by Django 4.2.20 on 2026-05-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_order_product_type_productionjob_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Size (mm)'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='grade',
            field=models.CharField(blank=True, max_length=20, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Size (mm)'),
        ),
    ]
