# Generated by Django 4.2.20 on 2026-05-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_order_size_producttype_grade_producttype_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10, unique=True)),
            ],
            options={
                'ordering': ['value'],
            },
        ),
    ]
