# Generated by Django 4.2.20 on 2026-07-05 20:08

from django.db import migrations

GRADES = ['EN8D', 'EN8', 'RAW', '430']
SIZES = ['0.23', '0.3', '1.0', '1.2', '1.5']


def seed_options(apps, schema_editor):
    GradeOption = apps.get_model('materials', 'GradeOption')
    SizeOption = apps.get_model('materials', 'SizeOption')
    for name in GRADES:
        GradeOption.objects.get_or_create(name=name)
    for value in SIZES:
        SizeOption.objects.get_or_create(value=value)


def remove_seeded_options(apps, schema_editor):
    GradeOption = apps.get_model('materials', 'GradeOption')
    SizeOption = apps.get_model('materials', 'SizeOption')
    GradeOption.objects.filter(name__in=GRADES).delete()
    SizeOption.objects.filter(value__in=SIZES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_gradeoption_sizeoption'),
    ]

    operations = [
        migrations.RunPython(seed_options, remove_seeded_options),
    ]
