# Generated by Django 4.2.20 on 2026-07-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_seed_grade_size_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttype',
            unique_together={('grade', 'size')},
        ),
    ]
