# Generated by Django 4.2.20 on 2026-09-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_alter_producttype_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
