# Generated by Django 4.2.20 on 2026-09-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_material_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='legacy_used_weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text="Weight already issued before this coil was tracked in the app — imported from the spreadsheet's ISSUED QTY columns. Added to weight cut via the app to compute total usage.", max_digits=10),
        ),
    ]
