# Generated by Django 4.2.20 on 2026-09-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0016_material_legacy_used_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_production', 'In Production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
    ]
