# Generated by Django 4.2.20 on 2026-09-15 09:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0017_alter_material_archived_at_alter_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=20, null=True)),
                ('total_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='invoice_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Fixed per-coil weight from the gate entry's invoice (total_weight ÷ total coils across all lots) — a rough average, not a measurement. `quantity` below is the actual measured weight and is what all usage is computed from.", max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='GateEntryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('no_of_coils', models.PositiveIntegerField()),
                ('gate_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='materials.gateentry')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='The gate entry lot (grade/size batch within a truck delivery) this coil was physically part of. Null for coils that predate gate entries (imported/historical data).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coils', to='materials.gateentrylot'),
        ),
    ]
