# Generated by Django 4.2.20 on 2026-09-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_gateentry_material_invoice_weight_gateentrylot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateentry',
            name='bill_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gateentry',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
