# Generated by Django 4.2.20 on 2026-09-16 08:14

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0021_swap_gateentry_vendor_gateentrylot_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCoilPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_allocated', models.DecimalField(decimal_places=3, max_digits=10)),
                ('picked_at', models.DateTimeField(auto_now_add=True)),
                ('coil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_picks', to='materials.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coil_picks', to='materials.order')),
            ],
        ),
        migrations.RemoveField(
            model_name='productionjob',
            name='part',
        ),
        migrations.AddField(
            model_name='allowedcoilspec',
            name='raw_material_ratio',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text="kg of this raw material needed to produce 1 kg of finished product (e.g. 1.100 = 10% wastage). Used to convert an order's required quantity into how much of this raw material needs to be picked.", max_digits=6, verbose_name='Raw material ratio'),
        ),
        migrations.AlterField(
            model_name='productionjob',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='materials.order'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CoilPart',
        ),
        migrations.AddField(
            model_name='productionjob',
            name='pick',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='materials.ordercoilpick'),
            preserve_default=False,
        ),
    ]
