# Generated by Django 4.2.20 on 2026-09-16 08:42

from django.db import migrations, models


def backfill_order_no(apps, schema_editor):
    """Existing orders never had an order_no — assign them sequentially in
    creation order, which also happens to compact any gaps already present
    from orders deleted before this field existed."""
    Order = apps.get_model('materials', 'Order')
    for i, order in enumerate(Order.objects.order_by('pk'), start=1):
        order.order_no = i
        order.save(update_fields=['order_no'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0022_ordercoilpick_remove_productionjob_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.PositiveIntegerField(editable=False, help_text='Displayed as ORD-####. Assigned sequentially on creation and kept gap-free — deleting an order renumbers every order after it down by one (see the post_delete receiver below), unlike coil_no/job_no which are never reused.', null=True, unique=True),
        ),
        migrations.RunPython(backfill_order_no, noop_reverse),
    ]
