# Generated by Django 4.2.20 on 2026-09-16 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0023_order_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateentry',
            name='bill_no',
        ),
    ]
