# Generated by Django 4.2.20 on 2026-09-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0026_query_order_source_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='query',
            name='source',
            field=models.CharField(choices=[('call', 'Phone Call'), ('referral', 'Referral'), ('indiamart', 'IndiaMART'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=20),
        ),
    ]
