# Generated by Django 4.2.30 on 2026-09-24 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0027_alter_query_company_name_alter_query_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_order',
            field=models.FileField(blank=True, help_text="Customer's own PO, if they attached one when filling the quote form.", null=True, upload_to='purchase_orders/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.PositiveIntegerField(editable=False, null=True, unique=True)),
                ('rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('size', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='materials.customer')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.producttype')),
                ('source_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='materials.query')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
