# Generated by Django 4.2.30 on 2026-09-25, hand-reordered so the data
# migration runs after QuotationLineItem exists but before the old
# rate_per_kg/product_type/grade/size fields are removed — otherwise any
# already-sent Quotation would lose that data with no line item to hold it.
from django.db import migrations, models
import django.db.models.deletion


def migrate_existing_quotations_to_line_items(apps, schema_editor):
    Quotation = apps.get_model('materials', 'Quotation')
    QuotationLineItem = apps.get_model('materials', 'QuotationLineItem')
    for quotation in Quotation.objects.all():
        description = quotation.product_type.item_code if quotation.product_type_id else (quotation.grade or 'Item')
        QuotationLineItem.objects.create(
            quotation=quotation,
            order=1,
            description=description,
            product_type_id=quotation.product_type_id,
            grade=quotation.grade or '',
            size=quotation.size,
            quantity=1,
            unit='KGS',
            rate_per_kg=quotation.rate_per_kg,
        )


def noop_reverse(apps, schema_editor):
    """Not reversible — the pre-migration rate_per_kg/product_type/grade/
    size fields no longer exist by the time this would run, so there's
    nothing to write the line items' data back into."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0028_order_purchase_order_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery_terms',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='freight_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='freight_terms',
            field=models.CharField(blank=True, default='The Same Shall be in your scope', max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='gst_terms',
            field=models.CharField(blank=True, default='Extra As Applicable', max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='insurance_terms',
            field=models.CharField(blank=True, default='Extra At actual to be borne by Customer', max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='kind_attn',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.CharField(blank=True, default='100% Advance', max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='pf_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='P&F amount'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='price_basis',
            field=models.CharField(blank=True, default='Ex-Works', max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='ref_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='rev_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='rev_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sales_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='same_state_as_us',
            field=models.BooleanField(default=True, help_text='Drives the GST split: CGST+SGST (half each) if checked, IGST if not.'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='validity_terms',
            field=models.CharField(blank=True, default='7 Days from date of offer', max_length=200),
        ),
        migrations.CreateModel(
            name='QuotationLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order (Sr. No.) within the quotation.')),
                ('description', models.CharField(max_length=255)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('size', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(default='KGS', max_length=20)),
                ('rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount %')),
                ('hsn_sac', models.CharField(blank=True, max_length=20, verbose_name='HSN/SAC')),
                ('gst_pct', models.DecimalField(decimal_places=2, default=18, max_digits=5, verbose_name='GST %')),
                ('tool_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('moq', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='MOQ')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.producttype')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='materials.quotation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RunPython(migrate_existing_quotations_to_line_items, noop_reverse),
        migrations.RemoveField(
            model_name='quotation',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='rate_per_kg',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='size',
        ),
    ]
