# Generated by Django 4.2.30 on 2026-09-30, with a hand-added data step:
# every Quotation that predates the 'status' field already has a real
# quotation_no, meaning it was actually sent under the old regime — mark
# those 'sent' rather than leaving them at the new default of 'draft',
# which would make them look editable/discardable when they're really
# permanent records of what was quoted.
from django.db import migrations, models


def mark_existing_quotations_sent(apps, schema_editor):
    Quotation = apps.get_model('materials', 'Quotation')
    Quotation.objects.filter(quotation_no__isnull=False).update(status='sent')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0029_quotation_line_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='quotationlineitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quotationlineitem',
            name='rate_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(mark_existing_quotations_sent, noop_reverse),
    ]
