# Generated by Django 4.2.30 on 2026-09-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0030_quotation_drafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
