# Generated by Django 4.2.30 on 2026-09-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0031_quotation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='drawing',
            field=models.FileField(blank=True, null=True, upload_to='query_drawings/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='query',
            name='drawing_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
