# Generated by Django 5.2.17 on 2026-10-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0032_query_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='delivery_form',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='query',
            name='end_use',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='query',
            name='frequency',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='query',
            name='gst_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='query',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='query',
            name='make',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='query',
            name='mechanical_properties',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='query',
            name='process_required',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='query',
            name='product_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='query',
            name='quantity_text',
            field=models.TextField(blank=True),
        ),
    ]
