# Generated by Django 5.2.17 on 2026-10-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0033_query_intake_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='delivery_form',
        ),
        migrations.RemoveField(
            model_name='query',
            name='end_use',
        ),
        migrations.RemoveField(
            model_name='query',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='query',
            name='make',
        ),
        migrations.RemoveField(
            model_name='query',
            name='mechanical_properties',
        ),
        migrations.RemoveField(
            model_name='query',
            name='process_required',
        ),
        migrations.AddField(
            model_name='query',
            name='end_use_delivery',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='query',
            name='technical_requirements',
            field=models.TextField(blank=True),
        ),
    ]
