# Generated by Django 5.2.17 on 2026-10-05 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0034_query_merged_intake_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{2}[A-Z]{5}\\d{4}[A-Z][1-9A-Z]Z[0-9A-Z]$', 'Enter a valid 15-character GST number.')]),
        ),
    ]
