# Generated by Django 5.2.17 on 2026-10-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0035_query_gst_number_validator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='end_use_delivery',
        ),
        migrations.AddField(
            model_name='query',
            name='delivery_form',
            field=models.CharField(blank=True, choices=[('Coil', 'Coil'), ('Bar', 'Bar')], max_length=10),
        ),
        migrations.AddField(
            model_name='query',
            name='end_use',
            field=models.TextField(blank=True),
        ),
    ]
