# Generated by Django 5.2.17 on 2026-10-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0036_query_split_end_use_and_delivery_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='referrer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='query',
            name='referrer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='query',
            name='source_detail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='query',
            name='source',
            field=models.CharField(choices=[('indiamart', 'IndiaMART'), ('google', 'Google'), ('referral', 'Referral'), ('other', 'Other'), ('whatsapp', 'WhatsApp'), ('call', 'Phone Call')], max_length=20),
        ),
    ]
