# Generated by Django 5.2.17 on 2026-10-05 10:00

from django.db import migrations, models


def backfill_sent_at(apps, schema_editor):
    # Quotations sent before this field existed: their last save is the best
    # record there is of when they went out.
    Quotation = apps.get_model('materials', 'Quotation')
    for quotation in Quotation.objects.filter(status='sent', sent_at__isnull=True):
        quotation.sent_at = quotation.updated_at
        quotation.save(update_fields=['sent_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0037_query_sources_and_referral_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(backfill_sent_at, migrations.RunPython.noop),
    ]
