# Generated by Django 5.2.17 on 2026-10-05 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0038_quotation_sent_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'product code', 'verbose_name_plural': 'product codes'},
        ),
        migrations.AlterField(
            model_name='order',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='materials.producttype', verbose_name='Product Code'),
        ),
    ]
