# Generated by Django 5.2.17 on 2026-10-05 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0039_product_code_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Order in menus and dropdowns (lowest first).')),
            ],
            options={
                'verbose_name': 'product type',
                'verbose_name_plural': 'product types',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='producttype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='producttype',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_codes', to='materials.productcategory', verbose_name='Product Type'),
        ),
        migrations.AddField(
            model_name='query',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.productcategory', verbose_name='Product Type'),
        ),
        migrations.AddField(
            model_name='quotationlineitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.productcategory', verbose_name='Product Type'),
        ),
        migrations.AddConstraint(
            model_name='producttype',
            constraint=models.UniqueConstraint(fields=('category', 'grade', 'size'), name='unique_code_per_type_grade_size'),
        ),
        migrations.AddConstraint(
            model_name='producttype',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True)), fields=('grade', 'size'), name='unique_untyped_code_per_grade_size'),
        ),
    ]
