# Generated by Django 5.2.17 on 2026-10-05 10:27

import django.core.validators
from django.db import migrations, models


# The 3-letter code each product type starts its product codes with.
TYPE_CODES = {
    'Key Steel': 'KEY', 'Steel Chamfer': 'SCH', 'Half Round Bright Bar': 'HRB', 'Flat Bright Bar': 'FBB',
    'Square Bright Bar': 'SQB', 'Round Bright Bar': 'RBB', 'Hexagonal Bright Bar': 'HXB',
    'Special Profiles Bar': 'SPB', 'Shaped Bright Bar': 'SHB', 'Triangle Bright Bar': 'TBB',
    'Profile Wire': 'PRW', 'Shaped Wire': 'SHW', 'Flat Wire': 'FLW', 'Cold Rolled Strip': 'CRS',
}


def fill_codes_and_numbers(apps, schema_editor):
    ProductCategory = apps.get_model('materials', 'ProductCategory')
    for name, code in TYPE_CODES.items():
        ProductCategory.objects.filter(name=name, code__isnull=True).update(code=code)
    # Number the grades that already exist, in the order they were created.
    GradeOption = apps.get_model('materials', 'GradeOption')
    for number, grade in enumerate(GradeOption.objects.filter(number__isnull=True).order_by('pk'), start=1):
        grade.number = number
        grade.save(update_fields=['number'])


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0041_seed_product_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeoption',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text='Used in product codes, 1-999. Assigned automatically when the grade is first used.', null=True, unique=True, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='code',
            field=models.CharField(help_text='Exactly 3 capital letters; the start of every product code of this type.', max_length=3, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Exactly 3 capital letters, e.g. FBB.')]),
        ),
        migrations.RunPython(fill_codes_and_numbers, migrations.RunPython.noop),
    ]
