# Generated by Django 5.2.17 on 2026-10-05 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0042_product_code_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer_gstin',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{2}[A-Z]{5}\\d{4}[A-Z][1-9A-Z]Z[0-9A-Z]$', 'Enter a valid 15-character GST number.')]),
        ),
    ]
