# Generated by Django 5.2.17 on 2026-10-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0046_normalized_grades'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=128, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='last_asked_field',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='query',
            name='last_inbound_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='query',
            name='review_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
