# Generated by Django 5.2.17 on 2026-10-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0047_whatsapp_resilience'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='bot_stage',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='query',
            name='edit_field',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='query',
            name='intake_confirmed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='pending_drawing',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='query_drawings/pending/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='query',
            name='pending_value',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
