# Generated by Django 5.2.17 on 2026-10-07 09:00

import django.core.validators
import materials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0048_whatsapp_review_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='drawing_file',
            field=models.FileField(blank=True, null=True, upload_to='order_drawings/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'webp', 'dwg', 'dxf', 'step', 'stp', 'igs', 'iges', 'zip']), materials.models.validate_drawing_size], verbose_name='Drawing'),
        ),
        migrations.AddField(
            model_name='order',
            name='other_tolerances',
            field=models.TextField(blank=True, verbose_name='Other tolerances'),
        ),
        migrations.AddField(
            model_name='order',
            name='thickness_tol_from',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Thickness tolerance from'),
        ),
        migrations.AddField(
            model_name='order',
            name='thickness_tol_to',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Thickness tolerance to'),
        ),
        migrations.AddField(
            model_name='order',
            name='width_tol_from',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Width tolerance from'),
        ),
        migrations.AddField(
            model_name='order',
            name='width_tol_to',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Width tolerance to'),
        ),
    ]
