# Generated by Django 5.2.17 on 2026-10-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0049_order_drawing_and_tolerances'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bar_length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Bar length (mm)'),
        ),
        migrations.AddField(
            model_name='order',
            name='coil_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Approx. coil weight (kg)'),
        ),
        migrations.AddField(
            model_name='order',
            name='length_tol_from',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Length tolerance from'),
        ),
        migrations.AddField(
            model_name='order',
            name='length_tol_to',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Length tolerance to'),
        ),
    ]
