# Generated by Django 5.2.17 on 2026-10-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0051_query_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedcoilspec',
            name='order_thickness',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Leave blank to apply whatever thickness is ordered.', max_digits=10, null=True, verbose_name='For ordered thickness (mm)'),
        ),
        migrations.AddField(
            model_name='allowedcoilspec',
            name='order_width',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Leave blank to apply whatever width is ordered.', max_digits=10, null=True, verbose_name='For ordered width (mm)'),
        ),
    ]
