# Generated by Django 5.2.17 on 2026-10-08 08:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0052_allowed_spec_order_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedcoilspec',
            name='order_thickness',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='For ordered thickness (mm)'),
        ),
        migrations.AlterField(
            model_name='allowedcoilspec',
            name='order_width',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='For ordered width (mm)'),
        ),
        migrations.AlterField(
            model_name='allowedcoilspec',
            name='raw_material_ratio',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=6, verbose_name='Raw material ratio'),
        ),
    ]
