# Generated by Django 5.2.17 on 2026-10-09 08:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def create_root_parts(apps, schema_editor):
    """Every existing job becomes one part (the whole picked coil) that carries all of its step history."""
    ProductionJob = apps.get_model('materials', 'ProductionJob')
    ProductionPart = apps.get_model('materials', 'ProductionPart')
    StepLog = apps.get_model('materials', 'StepLog')
    for job in ProductionJob.objects.select_related('pick'):
        part, _ = ProductionPart.objects.get_or_create(
            job=job, parent=None, defaults={'label': job.job_no, 'weight': job.pick.weight_allocated})
        StepLog.objects.filter(job=job, part__isnull=True).update(part=part)


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0055_product_details_per_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='joins_parts',
            field=models.BooleanField(default=False, verbose_name='all parts together'),
        ),
        migrations.AddField(
            model_name='processstep',
            name='splits_material',
            field=models.BooleanField(default=False, verbose_name='splits the material'),
        ),
        migrations.CreateModel(
            name='ProductionPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, unique=True)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('scrap_weight', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='materials.productionjob')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='materials.productionpart')),
                ('split_at_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='materials.processstep')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='steplog',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_logs', to='materials.productionpart'),
        ),
        migrations.RunPython(create_root_parts, migrations.RunPython.noop),
    ]
